export const techWords = [
  "Algorithm",
  "Analytics",
  "Artificial Intelligence",
  "API",
  "App",
  "Authentication",
  "Automation",
  "Augmented Reality",
  "Big Data",
  "Blockchain",
  "Backend",
  "Bandwidth",
  "Biometrics",
  "Bluetooth",
  "Bot",
  "Broadband",
  "Buffering",
  "Cloud",
  "Code",
  "Compiler",
];
